//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OfficeToImagesConverter4dots {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResTranslate {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResTranslate() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OfficeToImagesConverter4dots.ResTranslate", typeof(ResTranslate).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A new version has been released. Press the OK button to download the new version.
        /// </summary>
        internal static string A_new_version_has_been_released__Press_the_OK_button_to_download_the_new_version {
            get {
                return ResourceManager.GetString("A new version has been released. Press the OK button to download the new version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A new version has been released. Would you like to download it now ?.
        /// </summary>
        internal static string A_new_version_has_been_released__Would_you_like_to_download_it_now__ {
            get {
                return ResourceManager.GetString("A new version has been released. Would you like to download it now ?", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new search item to project.
        /// </summary>
        internal static string Add_new_search_item_to_project {
            get {
                return ResourceManager.GetString("Add new search item to project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Subdirectories ?.
        /// </summary>
        internal static string Add_Subdirectories__ {
            get {
                return ResourceManager.GetString("Add Subdirectories ?", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured !.
        /// </summary>
        internal static string An_error_occured__ {
            get {
                return ResourceManager.GetString("An error occured !", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure that you want clear the added files ?.
        /// </summary>
        internal static string Are_you_sure_that_you_want_clear_the_added_files__ {
            get {
                return ResourceManager.GetString("Are you sure that you want clear the added files ?", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attendere prego.
        /// </summary>
        internal static string Attendere_prego {
            get {
                return ResourceManager.GetString("Attendere prego", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio Applications.
        /// </summary>
        internal static string Audio_Applications {
            get {
                return ResourceManager.GetString("Audio Applications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitte warten.
        /// </summary>
        internal static string Bitte_warten {
            get {
                return ResourceManager.GetString("Bitte warten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business Version - Licensed.
        /// </summary>
        internal static string Business_Version___Licensed {
            get {
                return ResourceManager.GetString("Business Version - Licensed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change PDF Properties.
        /// </summary>
        internal static string Change_PDF_Properties {
            get {
                return ResourceManager.GetString("Change PDF Properties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Added Files ?.
        /// </summary>
        internal static string Clear_Added_Files__ {
            get {
                return ResourceManager.GetString("Clear Added Files ?", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue activated search?.
        /// </summary>
        internal static string Continue_activated_search_ {
            get {
                return ResourceManager.GetString("Continue activated search?", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desktop Applications.
        /// </summary>
        internal static string Desktop_Applications {
            get {
                return ResourceManager.GetString("Desktop Applications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Direct search started.
        /// </summary>
        internal static string Direct_search_started {
            get {
                return ResourceManager.GetString("Direct search started", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documents.
        /// </summary>
        internal static string Documents {
            get {
                return ResourceManager.GetString("Documents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download new version ?.
        /// </summary>
        internal static string Download_new_version__ {
            get {
                return ResourceManager.GetString("Download new version ?", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit 4dots Project.
        /// </summary>
        internal static string Edit_4dots_Project {
            get {
                return ResourceManager.GetString("Edit 4dots Project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erroneous search 2.
        /// </summary>
        internal static string Erroneous_search_2 {
            get {
                return ResourceManager.GetString("Erroneous search 2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error. Could not run new Setup File !.
        /// </summary>
        internal static string Error__Could_not_run_new_Setup_File__ {
            get {
                return ResourceManager.GetString("Error. Could not run new Setup File !", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error. File or Directory not found !.
        /// </summary>
        internal static string Error__File_or_Directory_not_found__ {
            get {
                return ResourceManager.GetString("Error. File or Directory not found !", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error 1.
        /// </summary>
        internal static string Error_1 {
            get {
                return ResourceManager.GetString("Error 1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error 12.
        /// </summary>
        internal static string Error_12 {
            get {
                return ResourceManager.GetString("Error 12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error 4.
        /// </summary>
        internal static string Error_4 {
            get {
                return ResourceManager.GetString("Error 4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Could not change Language !.
        /// </summary>
        internal static string Error_Could_not_change_Language__ {
            get {
                return ResourceManager.GetString("Error Could not change Language !", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error could not read file !.
        /// </summary>
        internal static string Error_could_not_read_file__ {
            get {
                return ResourceManager.GetString("Error could not read file !", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error could not Replace Image for Document.
        /// </summary>
        internal static string Error_could_not_Replace_Image_for_Document {
            get {
                return ResourceManager.GetString("Error could not Replace Image for Document", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error during search startup.
        /// </summary>
        internal static string Error_during_search_startup {
            get {
                return ResourceManager.GetString("Error during search startup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while processing List !.
        /// </summary>
        internal static string Error_while_processing_List__ {
            get {
                return ResourceManager.GetString("Error while processing List !", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error wrong file type !.
        /// </summary>
        internal static string Error_wrong_file_type__ {
            get {
                return ResourceManager.GetString("Error wrong file type !", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Management Applications.
        /// </summary>
        internal static string File_Management_Applications {
            get {
                return ResourceManager.GetString("File Management Applications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Graphics Applications.
        /// </summary>
        internal static string Graphics_Applications {
            get {
                return ResourceManager.GetString("Graphics Applications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Great application to Extract Images from Office Documents !.
        /// </summary>
        internal static string Great_application_to_Extract_Images_from_Office_Documents__ {
            get {
                return ResourceManager.GetString("Great application to Extract Images from Office Documents !", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import search result.
        /// </summary>
        internal static string Import_search_result {
            get {
                return ResourceManager.GetString("Import search result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Init Project.
        /// </summary>
        internal static string Init_Project {
            get {
                return ResourceManager.GetString("Init Project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is From Windows Explorer.
        /// </summary>
        internal static string Is_From_Windows_Explorer {
            get {
                return ResourceManager.GetString("Is From Windows Explorer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is necessary to upgrade to the latest version of the application. Press the OK button to download the new version.
        /// </summary>
        internal static string It_is_necessary_to_upgrade_to_the_latest_version_of_the_application__Press_the_OK_button_to_download_the_new_version {
            get {
                return ResourceManager.GetString("It is necessary to upgrade to the latest version of the application. Press the OK" +
                        " button to download the new version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MessageTitle.
        /// </summary>
        internal static string MessageTitle {
            get {
                return ResourceManager.GetString("MessageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MessageTitle7.
        /// </summary>
        internal static string MessageTitle7 {
            get {
                return ResourceManager.GetString("MessageTitle7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MessageTitle8.
        /// </summary>
        internal static string MessageTitle8 {
            get {
                return ResourceManager.GetString("MessageTitle8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation completed successfully !.
        /// </summary>
        internal static string Operation_completed_successfully__ {
            get {
                return ResourceManager.GetString("Operation completed successfully !", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation completed with Errors !.
        /// </summary>
        internal static string Operation_completed_with_Errors__ {
            get {
                return ResourceManager.GetString("Operation completed with Errors !", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation Stopped !.
        /// </summary>
        internal static string Operation_Stopped__ {
            get {
                return ResourceManager.GetString("Operation Stopped !", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other Applications.
        /// </summary>
        internal static string Other_Applications {
            get {
                return ResourceManager.GetString("Other Applications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overwrite Document.
        /// </summary>
        internal static string Overwrite_Document {
            get {
                return ResourceManager.GetString("Overwrite Document", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password Recovery.
        /// </summary>
        internal static string Password_Recovery {
            get {
                return ResourceManager.GetString("Password Recovery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PDF Applications.
        /// </summary>
        internal static string PDF_Applications {
            get {
                return ResourceManager.GetString("PDF Applications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal/EDU Version - Licensed.
        /// </summary>
        internal static string Personal_EDU_Version___Licensed {
            get {
                return ResourceManager.GetString("Personal/EDU Version - Licensed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please add a Document first !.
        /// </summary>
        internal static string Please_add_a_Document_first__ {
            get {
                return ResourceManager.GetString("Please add a Document first !", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please add only Office Files !.
        /// </summary>
        internal static string Please_add_only_Office_Files__ {
            get {
                return ResourceManager.GetString("Please add only Office Files !", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a Subfolder Name !.
        /// </summary>
        internal static string Please_enter_a_Subfolder_Name__ {
            get {
                return ResourceManager.GetString("Please enter a Subfolder Name !", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid Subfolder Name !.
        /// </summary>
        internal static string Please_enter_a_valid_Subfolder_Name__ {
            get {
                return ResourceManager.GetString("Please enter a valid Subfolder Name !", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please specify another option as the Output Folder !.
        /// </summary>
        internal static string Please_specify_another_option_as_the_Output_Folder__ {
            get {
                return ResourceManager.GetString("Please specify another option as the Output Folder !", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait.
        /// </summary>
        internal static string Please_wait {
            get {
                return ResourceManager.GetString("Please wait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor aguarde.
        /// </summary>
        internal static string Por_favor_aguarde {
            get {
                return ResourceManager.GetString("Por favor aguarde", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor espere.
        /// </summary>
        internal static string Por_favor_espere {
            get {
                return ResourceManager.GetString("Por favor espere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace string process started.
        /// </summary>
        internal static string Replace_string_process_started {
            get {
                return ResourceManager.GetString("Replace string process started", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Same Folder of Document.
        /// </summary>
        internal static string Same_Folder_of_Document {
            get {
                return ResourceManager.GetString("Same Folder of Document", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search duration process.
        /// </summary>
        internal static string Search_duration_process {
            get {
                return ResourceManager.GetString("Search duration process", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subfolder.
        /// </summary>
        internal static string Subfolder {
            get {
                return ResourceManager.GetString("Subfolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subfolder of Document.
        /// </summary>
        internal static string Subfolder_of_Document {
            get {
                return ResourceManager.GetString("Subfolder of Document", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Utilities.
        /// </summary>
        internal static string System_Utilities {
            get {
                return ResourceManager.GetString("System Utilities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The application will now exit and run the updated setup file.
        /// </summary>
        internal static string The_application_will_now_exit_and_run_the_updated_setup_file {
            get {
                return ResourceManager.GetString("The application will now exit and run the updated setup file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Trial Version of Office to Images Converter allows only 5 Document Images Extractions.\n\nPlease buy the Application for Unlimited Image Extractions and Unlimited Functionality.\n.
        /// </summary>
        internal static string The_Trial_Version_of_Office_to_Images_Converter_allows_only_5_Document_Images_Extractions__n_nPlease_buy_the_Application_for_Unlimited_Image_Extractions_and_Unlimited_Functionality__n {
            get {
                return ResourceManager.GetString("The Trial Version of Office to Images Converter allows only 5 Document Images Ext" +
                        "ractions.\\n\\nPlease buy the Application for Unlimited Image Extractions and Unli" +
                        "mited Functionality.\\n", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is the latest version !.
        /// </summary>
        internal static string This_is_the_latest_version__ {
            get {
                return ResourceManager.GetString("This is the latest version !", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        internal static string Total {
            get {
                return ResourceManager.GetString("Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trial Version - Unlicensed.
        /// </summary>
        internal static string Trial_Version___Unlicensed {
            get {
                return ResourceManager.GetString("Trial Version - Unlicensed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uniform process.
        /// </summary>
        internal static string Uniform_process {
            get {
                return ResourceManager.GetString("Uniform process", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unspecified Error.
        /// </summary>
        internal static string Unspecified_Error {
            get {
                return ResourceManager.GetString("Unspecified Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veuillez patienter.
        /// </summary>
        internal static string Veuillez_patienter {
            get {
                return ResourceManager.GetString("Veuillez patienter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video Applications.
        /// </summary>
        internal static string Video_Applications {
            get {
                return ResourceManager.GetString("Video Applications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Webdesign Applications.
        /// </summary>
        internal static string Webdesign_Applications {
            get {
                return ResourceManager.GetString("Webdesign Applications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to add also Subdirectories ?.
        /// </summary>
        internal static string Would_you_like_to_add_also_Subdirectories__ {
            get {
                return ResourceManager.GetString("Would you like to add also Subdirectories ?", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your trial period of the application has expired ! Please Click on the Buy Button to Buy the Application !.
        /// </summary>
        internal static string Your_trial_period_of_the_application_has_expired___Please_Click_on_the_Buy_Button_to_Buy_the_Application__ {
            get {
                return ResourceManager.GetString("Your trial period of the application has expired ! Please Click on the Buy Button" +
                        " to Buy the Application !", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Αλλαγή Ονόματος.
        /// </summary>
        internal static string Αλλαγή_Ονόματος {
            get {
                return ResourceManager.GetString("Αλλαγή Ονόματος", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Αλλαγή στοιχείων εικόνας.
        /// </summary>
        internal static string Αλλαγή_στοιχείων_εικόνας {
            get {
                return ResourceManager.GetString("Αλλαγή στοιχείων εικόνας", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Αλλαγή Φίλτρου Εικόνας.
        /// </summary>
        internal static string Αλλαγή_Φίλτρου_Εικόνας {
            get {
                return ResourceManager.GetString("Αλλαγή Φίλτρου Εικόνας", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ανανέωση Εικόνας.
        /// </summary>
        internal static string Ανανέωση_Εικόνας {
            get {
                return ResourceManager.GetString("Ανανέωση Εικόνας", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Εισαγωγή Εικόνας.
        /// </summary>
        internal static string Εισαγωγή_Εικόνας {
            get {
                return ResourceManager.GetString("Εισαγωγή Εικόνας", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Εναλλαγή Εικόνας.
        /// </summary>
        internal static string Εναλλαγή_Εικόνας {
            get {
                return ResourceManager.GetString("Εναλλαγή Εικόνας", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Καθορισμός Ονόματος.
        /// </summary>
        internal static string Καθορισμός_Ονόματος {
            get {
                return ResourceManager.GetString("Καθορισμός Ονόματος", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Μορφοποίηση Εικόνας.
        /// </summary>
        internal static string Μορφοποίηση_Εικόνας {
            get {
                return ResourceManager.GetString("Μορφοποίηση Εικόνας", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Νέα Εικόνα.
        /// </summary>
        internal static string Νέα_Εικόνα {
            get {
                return ResourceManager.GetString("Νέα Εικόνα", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Παράμετροι Μετρήσεως Εικόνας.
        /// </summary>
        internal static string Παράμετροι_Μετρήσεως_Εικόνας {
            get {
                return ResourceManager.GetString("Παράμετροι Μετρήσεως Εικόνας", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Περιγραφή Ονόματος.
        /// </summary>
        internal static string Περιγραφή_Ονόματος {
            get {
                return ResourceManager.GetString("Περιγραφή Ονόματος", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Πηγή Εικόνας.
        /// </summary>
        internal static string Πηγή_Εικόνας {
            get {
                return ResourceManager.GetString("Πηγή Εικόνας", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Προβολή Εικόνας 1.
        /// </summary>
        internal static string Προβολή_Εικόνας_1 {
            get {
                return ResourceManager.GetString("Προβολή Εικόνας 1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Προβολή Εικόνων.
        /// </summary>
        internal static string Προβολή_Εικόνων {
            get {
                return ResourceManager.GetString("Προβολή Εικόνων", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Σφάλμα 120.
        /// </summary>
        internal static string Σφάλμα_120 {
            get {
                return ResourceManager.GetString("Σφάλμα 120", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Σφάλμα 1201.
        /// </summary>
        internal static string Σφάλμα_1201 {
            get {
                return ResourceManager.GetString("Σφάλμα 1201", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Υπολογισμός Επιφάνειας.
        /// </summary>
        internal static string Υπολογισμός_Επιφάνειας {
            get {
                return ResourceManager.GetString("Υπολογισμός Επιφάνειας", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Φίλτρο Εικόνας.
        /// </summary>
        internal static string Φίλτρο_Εικόνας {
            get {
                return ResourceManager.GetString("Φίλτρο Εικόνας", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пожалуйста подождите.
        /// </summary>
        internal static string Пожалуйста_подождите {
            get {
                return ResourceManager.GetString("Пожалуйста подождите", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to しばらくお待ちください.
        /// </summary>
        internal static string しばらくお待ちください {
            get {
                return ResourceManager.GetString("しばらくお待ちください", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请稍后.
        /// </summary>
        internal static string 请稍后 {
            get {
                return ResourceManager.GetString("请稍后", resourceCulture);
            }
        }
    }
}
